### ISSUE TITLE
[Suggestion] Ex command prefix :Repl should be :Reply

### ISSUE THREAD

**Issue by thinca** [rhysd/reply.vim#1]
This is not a request.  Just a suggestion.  Please close freely if you can not agree.

There is already [repl.vim](https://github.com/ujihisa/repl.vim) in the world and `:Repl` is already defined.

I think Ex command prefix should be plugin name like `:Reply` or `:ReplyXxx`.

- To avoid name conflicts.
- Clear for the user and less confusion.

What do you think?

**Comment by rhysd** [comment]
Thank you for the suggestion and I'm sorry for the huge delay (actually I did not notice this until notified directly).

It would be reasonable to avoid conflict in general. But I believe it's very rare case where both plugins are installed at the same time. So I want to go forward as-is for now.

Let me note that you can avoid conflict by writing configuration in your vimrc as follows:

```vim
" Do not define all commands
let g:loaded_reply = 1

command! -nargs=* -bang -range=0 -complete=customlist,reply#command#completion_start Reply call reply#command#start([<f-args>], <bang>0, <q-mods>, <count> != 0, <line1>, <line2>)
command! -nargs=0 -bang ReplyStop call reply#command#stop(<bang>0)
command! -nargs=* -range ReplySend call reply#command#send(<q-args>, <line1>, <line2>)
command! -nargs=0 -bar ReplyList call reply#command#list()
command! -nargs=0 -bar -range=0 ReplyRecv call reply#command#recv(<count> != 0, <line1>, <line2>)
command! -nargs=* -bang -range=0 -complete=customlist,reply#command#completion_start ReplyAuto call reply#command#auto([<f-args>], <bang>0, <q-mods>, <count> != 0, <line1>, <line2>)
```
