### ISSUE TITLE
How to start Repl with python virtualenv?

### ISSUE THREAD

**Issue by ipsod** [rhysd/reply.vim#7]
Hi.  How can I have reply.vim activate a python virtualenv before opening a repl?

**Comment by rhysd** [comment]
How reply.vim determines which virtual env directory should be activated? There may be multiple envs. I don't think it can be done automatically. You should activate one before starting vim.

**Comment by ipsod** [comment]
That would be trouble, as I change virtualenv's much more often than I change Vim instances, and I'm often well into an editing session before I realize I need to use a virtualenv.  If I could prefix `ptpython` with `workon myvirtualenv && `, it'd solve my problem.  Maybe if there was a variable, like `g:reply_repl_cmd_prefix`, or a command option, `Repl -prefix="workon myvirtualenv && "`?

I tried doing this: `let g:reply_repls = { 'python': ['workon nvim && ptpython'] }`, but when I tried running `:Repl`, I got an error stating: `reply.vim: No REPL is available for filetype 'python'. Candidates are ['workon nvim && ptpython']`

Maybe something that could accomplish this is already built in, and I'm just missing it?

**Comment by rhysd** [comment]
When string value is set to `g:reply_repls`, it only accepts REPL name, not a command. This plugin provides cusotmization point as `g:reply_repl_{repl}_executable` variable. How about following?

```vim
let g:reply_repl_ptpython_executable = 'workon myvirtualenv && ptpython'
```

I'm not sure `&&` works fine though.

**Comment by rhysd** [comment]
No response
