### ISSUE TITLE
Help with passing args to a Repl please.

### ISSUE THREAD

**Issue by megalithic** [rhysd/reply.vim#8]
Hi there, I'd like to set up 2 repls for elixir.

One for when you have a mix file in your directory and one when you don't. More simply, i'd be happy with just calling `:Repl iex -S mix` but this doesn't work. The docs show `:Repl {REPL} [{args...}]` but i'm not sure what format the args should be in when passed in. Any suggestions would be awesome! Thanks !!

**Comment by rhysd** [comment]
~~If you want to pass the arguments always, `g:reply_repl_{repl}_command_options` variable is available.~~

```vim
let g:reply_repl_iex_command_options = ['-S', 'mix']
```

~~Is this useful for you? Or do you want to pass arguments flexibly on each `:Repl` command execution?~~

In my environment, `{args}` of `:Repl {REPL} [{args...}]` works fine. I confirmed it with `irb` (standard Ruby interpreter) as follows.

1. `:Repl irb -r json`
2. `irb` opens in terminal window
3. Run `JSON.load('{"foo": 42}')`

Please describe what happens on your 'this doesn't work' actually.

**Comment by rhysd** [comment]
I'm not an Elixir user so please do not assume I have any knowledge about it.

**Comment by rhysd** [comment]
No response
